### ISSUE TITLE
Scraping Posts gives a 400 Bad Request

### ISSUE THREAD

**Issue by BlinkyStitt** [veeso/instagram-scraper-rs#2]
I got this working a few weeks ago, but it has broken again.

```
% INSTAGRAM_USERNAME=XXX INSTAGRAM_PASSWORD=XXX cargo run --example scraper XXX

...

     Running `target/debug/examples/scraper XXX`
authenticating with username XXX
XXX:  (followers: 96; following 151) - user id: XXX
there are 0 stories for XXX
there are 0 highlighted stories for XXX
Error: HTTP request response has a bad status code: 400 Bad Request
```

Looking at instagram.com and checking the developer console, it looks like the "variables" have changed.

Also, maybe related, they are deprecating the "Instagram Basic Display API"

**Comment by veeso** [comment]
Yep, it doesn't work anymore. The API has changed and basically nobody out there knows how to scrape with the api anymore. Probably they've finally prevented it from happening.
